.Dd August 2, 2016
.Dt LLOGGER 1
.Os Swarm-GDP
.Sh NAME
.Nm llogger
.Nd timestamp output lines for local log files
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Fl s Ar sigfigs
.Op Fl t
.Op Fl u
.Op Ar file-name
.Sh DESCRIPTION
.Nm
is similar to a non-syslog version of
.Xr logger 1 .
It reads data from the standard input,
timestamps it,
and writes it to the indicated output
.Ar file-name .
If the
.Ar file-name
is removed or renamed it is re-created;
this makes it possible to rotate log files
without restarting the process being logged.
If
.Ar file-name
is omitted it defaults to the standard output;
this just timestamps text lines.
.Sh OPTIONS
.Bl -tag
.
.It Fl a
Append to output
.Ar file-name .
Normally the output is overwritten.
.
.It Fl s Ar sigfigs
Output the indicated number of digits of fractional seconds.
The default is 6.
.
.It Fl t
In addition to logging,
.Dq tee
the output to stdout.
.
.It Fl u
Show dates in UTC instead of local time.
.El
.\".Sh EXIT STATUS
.\".Sh ENVIRONMENT
.\".Sh FILES
.Sh SEE ALSO
.Xr logger 1
.\".Sh EXAMPLES
.\".Sh BUGS
