ALL=		java js python

all:
	(cd python &&	${MAKE} all)
	(cd java &&	${MAKE} all)
	(cd js &&	${MAKE} all)

update-license:
	(cd python &&	${MAKE} update-license)
#	(cd java &&	${MAKE} update-license)
#	(cd js &&	${MAKE} update-license)
