
ALL=		gdp-client.deb \
		gdp-dev-c.deb \
		gdp-server.deb \

all: ${ALL}

gdp-client.deb:
	sh client-makepackage.sh

gdp-dev-c.deb:
	sh dev-c-makepackage.sh

gdp-server.deb:
	sh server-makepackage.sh
