#
#  Makefile for gdp/lang/js/apps/  (based on gdp/Makefile)
#
#	$Id$
#
#	Copyright (c) 2014, <TBD>.  All rights reserved.
#

# Alec Dara-Abrams
# 2014-11-04
#
# TBD: Copyrights, one-button tests
#
# Caveats:
#
#    This Makefile assumes that it is located in gdp/lang/js/apps/ ,
#    where gdp/ is a GDP Git local repository.
#
#    It will not force a re-build of the system up in gdp/ .
#    gdp/ must be re-built and kept up to date separately.
#
#    It invokes corresponding builds in sub-directory gdpREST_server. .


# External makefile targets below: all, clean, run (TBD)
# TBD: provide a test/ sub-directory.


# Internal makefile variables
#   None, currently.


# External makefile targets: all, clean, run (TBD)

all:
	@echo 'Nothing to make locally here - only JavaScript programs.'
	@echo 'See the README here as well as the js/tests/ README.'
	@echo 'for details on how to run the JS programs here.'
	(cd gdpREST_server; make clean all)

clean:
	# nothing to clean locally
	(cd gdpREST_server; make clean )

run:
	@echo 'See the README here as well as the js/tests/ README.'
	@echo 'for details on how to run the JS programs here.'

tags:
	# Placeholder to remind us of the utility of tag files

